### ISSUE TITLE
Enable error and counter logging into an SQL database

### ISSUE THREAD

**Issue by phil-lgr** [dabana/movehome#1]
_From @dabana on August 29, 2017 17:6_

_Copied from original issue: phil-lgr/movehome#40_

**Comment by phil-lgr** [comment]
_From @dabana on August 30, 2017 14:50_

Managed to update the database when errors are reseted. Still have problems updating the table view (probably because of variable scope issues). When I quit app and reload it, I can see the new entries to the database.

**Comment by dabana** [comment]
done
