### ISSUE TITLE
Setup Electron and Fluxbox for running the UI on the modules

### ISSUE THREAD

**Issue by phil-lgr** [dabana/movehome#7]
_From @phil-lgr on June 25, 2017 20:8_

_Copied from original issue: phil-lgr/movehome#1_

**Comment by phil-lgr** [comment]
_From @dabana on August 3, 2017 17:35_

On le met-tu dans le container du front?
On installe tu sur l'image de base (UDOO ou Raspberry Pi?)
On va tu avoir besoin d'un setup file specifique à chaque écran?

**Comment by phil-lgr** [comment]
_From @dabana on August 3, 2017 19:24_

Quelques lectures:
https://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container
https://stackoverflow.com/questions/39930223/how-to-run-an-electron-app-on-docker
https://medium.com/@calbertts/developing-electron-apps-in-macos-afd21b4a59e3
Mais ça c'est une bible:
http://wiki.ros.org/docker/Tutorials/GUI
Le gars est in peu fou:
https://blog.jessfraz.com/post/docker-containers-on-the-desktop/
Containerized browsers!
https://github.com/sameersbn/docker-browser-box
https://hub.docker.com/r/sameersbn/browser-box/

**Comment by dabana** [comment]
BackNet project suspended
