### ISSUE TITLE
RESTfulize the django API myserver with the REST framework

### ISSUE THREAD

**Issue by phil-lgr** [dabana/movehome#8]
_From @dabana on July 28, 2017 13:43_

# Notes on how to RESTfulize a django project

1) Use a serializer class instead of a form
2) Use Request and Response object from the REST framework
3) Use explicit status codes from the REST framework
4) Use the format=None keyword
5) Change views to class-based views
6) Use mixins to further reduce the code needed the create views
7) Add user traceability and permissions to the database

_Copied from original issue: phil-lgr/movehome#6_

**Comment by dabana** [comment]
BackNet project suspended
